import json
import Connectors
import Transformations
import AutoML
try:
    EstimationofBikeRentals_DBFS = Connectors.DBFSConnector.fetch(
        [], {}, "5e9d9046e3127dd4c3d893ae", spark, "{'url': '/Demo/Demand_Estimate_ Bike_Rental.csv', 'file_type': 'Delimeted', 'dbfs_token': 'dapib8073bbfa952efa9d363b234ce06e2c6', 'dbfs_domain': 'westus.azuredatabricks.net', 'delimiter': ',', 'is_header': 'Use Header Line'}")

except Exception as ex:
    print(ex)
try:
    EstimationofBikeRentals_AutoFE = Transformations.TransformationMain.run(["5e9d9046e3127dd4c3d893ae"], {"5e9d9046e3127dd4c3d893ae": EstimationofBikeRentals_DBFS}, "5e9d9046e3127dd4c3d893af", spark, json.dumps({"FE": [{"transformationsData": {}, "feature": "instant", "transformation": "", "type": "numeric", "replaceby": "mean", "selected": "True", "stats": {"count": "8834", "mean": "8728.16", "stddev": "5015.34", "min": "5", "max": "17378", "missing": "0"}}, {"transformationsData": {"feature_label": "dteday"}, "feature": "dteday", "type": "date", "selected": "True", "replaceby": "random", "stats": {"count": "", "mean": "", "stddev": "", "min": "", "max": "", "missing": "0"}, "transformation": "Extract Date"}, {"transformationsData": {}, "feature": "season", "transformation": "", "type": "numeric", "replaceby": "mean", "selected": "True", "stats": {"count": "8834", "mean": "2.51", "stddev": "1.11", "min": "1", "max": "4", "missing": "0"}}, {"transformationsData": {}, "feature": "yr", "transformation": "", "type": "numeric", "replaceby": "mean", "selected": "True", "stats": {"count": "8834", "mean": "0.51", "stddev": "0.5", "min": "0", "max": "1", "missing": "0"}}, {"transformationsData": {}, "feature": "mnth", "transformation": "", "type": "numeric", "replaceby": "mean", "selected": "True", "stats": {"count": "8834", "mean": "6.56", "stddev": "3.44", "min": "1", "max": "12", "missing": "0"}}, {"transformationsData": {}, "feature": "hr", "transformation": "", "type": "numeric", "replaceby": "mean", "selected": "True", "stats": {"count": "8834", "mean": "11.56", "stddev": "6.93", "min": "0", "max": "23", "missing": "0"}}, {"transformationsData": {}, "feature": "holiday", "transformation": "", "type": "numeric", "replaceby": "mean", "selected": "True", "stats": {"count": "8834", "mean": "0.03", "stddev": "0.17", "min": "0", "max": "1", "missing": "0"}}, {"transformationsData": {}, "feature": "weekday", "transformation": "", "type": "numeric", "replaceby": "mean", "selected": "True", "stats": {"count": "8834", "mean": "2.97", "stddev": "2.01", "min": "0", "max": "6", "missing": "0"}}, {"transformationsData": {}, "feature": "workingday", "transformation": "", "type": "numeric", "replaceby": "mean", "selected": "True", "stats": {"count": "8834", "mean": "0.68", "stddev": "0.47", "min": "0", "max": "1", "missing": "0"}}, {"transformationsData": {}, "feature": "weathersit", "transformation": "", "type": "numeric", "replaceby": "mean", "selected": "True", "stats": {
                                                                            "count": "8834", "mean": "1.43", "stddev": "0.64", "min": "1", "max": "4", "missing": "0"}}, {"transformationsData": {}, "feature": "temp", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "8834", "mean": "0.5", "stddev": "0.19", "min": "0.02", "max": "0.98", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "atemp", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "8834", "mean": "0.48", "stddev": "0.17", "min": "0.0", "max": "1.0", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "hum", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "8834", "mean": "0.63", "stddev": "0.19", "min": "0.0", "max": "1.0", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "windspeed", "type": "real", "selected": "True", "replaceby": "mean", "stats": {"count": "8834", "mean": "0.19", "stddev": "0.12", "min": "0.0", "max": "0.8358", "missing": "0"}, "transformation": ""}, {"transformationsData": {}, "feature": "casual", "transformation": "", "type": "numeric", "replaceby": "mean", "selected": "True", "stats": {"count": "8834", "mean": "35.34", "stddev": "48.93", "min": "0", "max": "355", "missing": "0"}}, {"transformationsData": {}, "feature": "registered", "transformation": "", "type": "numeric", "replaceby": "mean", "selected": "True", "stats": {"count": "8834", "mean": "152.62", "stddev": "150.73", "min": "0", "max": "885", "missing": "0"}}, {"transformationsData": {}, "feature": "cnt", "transformation": "", "type": "numeric", "replaceby": "mean", "selected": "True", "stats": {"count": "8834", "mean": "187.96", "stddev": "180.65", "min": "1", "max": "976", "missing": "0"}}, {"feature": "dteday_dayofmonth", "transformation": "", "transformationsData": {}, "type": "numeric", "generated": "True", "selected": "True", "stats": {"count": "8834", "mean": "15.68", "stddev": "8.76", "min": "1", "max": "31", "missing": "0"}}, {"feature": "dteday_month", "transformation": "", "transformationsData": {}, "type": "numeric", "generated": "True", "selected": "True", "stats": {"count": "8834", "mean": "6.56", "stddev": "3.44", "min": "1", "max": "12", "missing": "0"}}, {"feature": "dteday_year", "transformation": "", "transformationsData": {}, "type": "numeric", "generated": "True", "selected": "True", "stats": {"count": "8834", "mean": "2011.51", "stddev": "0.5", "min": "2011", "max": "2012", "missing": "0"}}]}))

except Exception as ex:
    print(ex)
try:
    AutoML.functionRegression(EstimationofBikeRentals_AutoFE, ["instant", "dteday", "season", "yr", "mnth", "hr", "holiday",
                                                               "weekday", "workingday", "weathersit", "temp", "atemp", "hum", "windspeed", "casual", "registered"], "cnt")

except Exception as ex:
    print(ex)
